name: Deploy to Cloud Run Prod
on:
  push:
    tags:
      - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn ci
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ${{ secrets.IMAGE_NAME_PROD }}
          tags: latest, $GITHUB_SHA
          registry: ${{ secrets.DOCKER_REGISTRY_PROD }}
          dockerfile: Dockerfile
          username: _json_key
          password: ${{ secrets.GCP_SA_JSON_PROD }}
      - uses: google-github-actions/deploy-cloudrun@main
        name: Update Cloud Run service
        with:
          credentials: ${{ secrets.GCP_SA_JSON_PROD }}
          image: ${{ secrets.DOCKER_REGISTRY_PROD }}/${{ secrets.GCP_SA_JSON_PROD }}:${{ github.sha }}
          service: ${{ secrets.CLOUD_RUN_SERVICE_PROD }}
          region: ${{ secrets.CLOUD_RUN_REGION_PROD }}
